Repository wooga/atlas-unity-version-manager, pull requests merged in 2021-11, with the labels that each got.

#33 Fix integration tests
  Jenkinsfile
  build.gradle
  src/integrationTest/groovy/wooga/gradle/unity/version/manager/IntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/version/manager/UvmCheckInstalltionIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/unity/version/manager/UvmInstallUnityIntegrationSpec.groovy
Labels: fix, atlas-stream

#31 Updated atlas plugin to 2.2.0
  Jenkinsfile
  build.gradle
Labels: update, new, atlas-stream

#30 Improve buildRequiredUnityComponents property convention
  src/main/groovy/wooga/gradle/unity/version/manager/UnityVersionManagerPlugin.groovy
  src/main/groovy/wooga/gradle/unity/version/manager/tasks/UvmCheckInstallation.groovy
Labels: improve, atlas-stream
